# automatically generated by the FlatBuffers compiler, do not modify

# namespace: sample

# /// To identify what instrumentation mode the data comes from
class InstMode(object):
    GVT = 0
    VT = 1
    RT = 2
    ET = 3

